### ISSUE TITLE
fsf-binutils unstable download

### ISSUE THREAD

**Issue by zhliang-work** [chipsalliance/rocket-tools#13]
Hi
I am wondering whether the FSF GDB submodule is necessary here. I found that this submodule cannot be downloaded smoothly. No matter I use an IP from China, the US, or other countries, it is very possible that the download process will be blocked for unknown reasons.
If I use an AWS machine, I got this error:
`Cloning into '/home/ubuntu/rocket-tools/fsf-binutils-gdb'...
fatal: read error: Connection reset by peer
fatal: clone of 'git://sourceware.org/git/binutils-gdb.git' into submodule path '/home/ubuntu/rocket-tools/fsf-binutils-gdb' failed
Failed to clone 'fsf-binutils-gdb'. Retry scheduled
`
For other cases, I just got stuck.

BTW, can we just use riscv-tools to replace this repo?

**Comment by vermicelli** [comment]
you can try 'http://' instead of 'git://'.

**Comment by totnine** [comment]
There are several FSF GDB mirrors on Github, just modifying the .gitmodules reference url and try again.
