### ISSUE TITLE
 Error: unrecognized opcode `fence.i'

### ISSUE THREAD

**Issue by srsorry** [chipsalliance/rocket-tools#17]
Hello.
When I build the rocket-tools prj by ./build, it return error with unrecognized opcode fence.i' on rocket.pk. The error information below：
 Removing existing riscv-pk/build directory Configuring project riscv-pk Building project riscv-pk ../dummy_payload/dummy_entry.S: Assembler messages: ../dummy_payload/dummy_entry.S:23: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:24: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:25: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:26: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:27: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:28: Warning: unterminated string; newline inserted ../dummy_payload/dummy_entry.S:29: Warning: unterminated string; newline inserted ../machine/mentry.S: Assembler messages: ../machine/mentry.S:93: Error: unrecognized opcode fence.i'
gmake: *** [mentry.o] Error 1
gmake: *** Waiting for unfinished jobs....
../machine/flush_icache.c: Assembler messages:
../machine/flush_icache.c:4: Error: unrecognized opcode `fence.i'
gmake: *** [flush_icache.o] Error 1

**Comment by aswaterman** [comment]
This is a cross-post from https://github.com/riscv-software-src/riscv-pk/issues/260
