### ISSUE TITLE
mkdir: missing operand Try 'mkdir --help' for more information.

### ISSUE THREAD

**Issue by whrudwns** [chipsalliance/rocket-tools#22]
I running build.sh in Ubuntu but there is an Error

![1](https://user-images.githubusercontent.com/81662197/182526714-6b68c9e6-a321-4027-abba-59194e1c4dbb.png)

**Comment by whrudwns** [comment]
It's my fault sry

**Comment by junxian-li-hpc** [comment]
Hello, I also encountered this issue. May I ask how you resolved it?

![image](https://github.com/chipsalliance/rocket-tools/assets/45509716/f5ca90a0-0dfa-49e4-b960-b71125c87a89)


> I running build.sh in Ubuntu but there is an Error
> 
> ![1](https://user-images.githubusercontent.com/81662197/182526714-6b68c9e6-a321-4027-abba-59194e1c4dbb.png)
