### ISSUE TITLE
[Proposal] Bump dependencies automatically by dependabot

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [chipsalliance/rocket-tools#25]
Bumping git submodules manually is a huge burden for maintainers, especially for toolchain repo like this.

[Dependabot can bump git submodules](
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem). As toolchain is not likely to break most of the time, automatic bump is acceptable.

As for regression, the building part of the [proposed nightly release flow](https://github.com/chipsalliance/rocket-tools/pull/24) could be a test.

**Comment by sequencer** [comment]
#27 #28 #29 #30 #31 looks good ;p
