### ISSUE TITLE
Error building rocket-tools on Ubuntu 20.04

### ISSUE THREAD

**Issue by qianfei11** [chipsalliance/rocket-tools#79]
Building rocket-tools on Ubuntu 20.04 with this error: 

```
$ export MAKEFLAGS=" -j20"
$ ./build.sh
...
../machine/flush_icache.c: Assembler messages:
../machine/flush_icache.c:4: Error: unrecognized opcode `fence.i', extension `zifencei' required
make: *** [Makefile:336: flush_icache.o] Error 1
make: *** Waiting for unfinished jobs....
../machine/mentry.S: Assembler messages:
../machine/mentry.S:93: Error: unrecognized opcode `fence.i', extension `zifencei' required
make: *** [Makefile:336: mentry.o] Error 1
```

It seems that I need to add `zifencei` extension. How to fix this error?

**Comment by junxian-li-hpc** [comment]
This might help：
https://github.com/chipsalliance/rocket-tools/issues/17#issue-1109967910

**Comment by 0xbbdd** [comment]
> This might help： [#17 (comment)](https://github.com/chipsalliance/rocket-tools/issues/17#issue-1109967910)

Thanks. Adding `--with-arch=rv64gc_zifencei` in the `build.sh` script works.
